# Generated by Django 4.2.17 on 2025-01-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
