# Generated by Django 4.2.17 on 2025-01-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_incident_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='incident_attachments/', verbose_name='Attachment'),
        ),
    ]
